### ISSUE TITLE
Example Crashes Code on Server

### ISSUE THREAD

**Issue by PrescottJRynewicz** [MartinGentleman/conditional-expression#1]
Hi Martin! 

I just commented on your medium post about the package, and downloaded it to test it. 

I run Node and tested the code server side. There is an example that uses `window.alert(...)`. This causes the package to crash on the server. 

Requesting the removal of the example for use on the server side. 
@MartinGentleman

**Comment by MeetMartin** [comment]
Hi

Thank shouldnt have been there, I will go ahead and remove it right now.

Thank you
Martin

**Comment by MeetMartin** [comment]
The issue should be resolved now. On https://www.npmjs.com/package/conditional-expression <https://www.npmjs.com/package/conditional-expression> I can see the new version and it also has couple more functions for comparing sizes.

My mistake was in webpack config, it seems that by default it tries to attach the package to window object. That was fixes. Please let me know if everything is working for you.

Martin
